
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    username: root
    password: 166066
    url: jdbc:mysql://localhost:3306/campus-trading-platform?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 12000
